---
output:
  pdf_document: default
  html_document: default
---
Title: Rcode for week 6 Joint Exercise

Subtitle: POLI502 Models of Political Analysis

Author: Conor Craig

Date: 10-03-2023


```{r}
# set seed for replication
set.seed(1)
# create an empty vector to store the birthday matches
match <- 0
# number of person we're looking for matches from
n <- 100
# number of simulations ran (went low due to my computer)
sam = 1000
# Actual simulation code
for(i in 1:sam) {
# 1:365 is choosing a random number between 1 - 365
# n is the number of elements within the sample
  bdays <- sample(1:365, n, replace = TRUE)
# birthdays are put on a table so that matches can be determined.
  bday_2 <- table(bdays)
#this is saying that if there are three or more matches, to add it to the match vector
  if(any(bday_2 >= 3)) {
    match <- match + 1
  }
}
#the number of matches divided by the number of simulations to determine the probability
birth_match <- match /sam
print (birth_match)
```

```{r}
# set seed for replication
set.seed(90)
# creating empty vectors to store values
stay_wins <- 0
switch_wins <- 0
# number of simulations
sims <- 1000
# actual simulation code
for (i in 1:sims) {
# the right door and the first choice are both a random door 1 - 3
  right_door <- sample(1:3, 1)
 first_choice <- sample(1:3, 1)
# the revealed door is different (setdiff) from the first door and right door
  revealed_door <- sample(setdiff(1:3, c(first_choice, right_door)), 1)
# the remaining door can either be the right door or another goat but can't be the
# first door or the revealed door
  remaining_door <- setdiff(1:3, c(first_choice, revealed_door))
# if else statement used to tally up the wins from staying and the wins from switching
  if (first_choice == right_door) {
# number of wins by staying
    stay_wins <- stay_wins + 1
  } else {
# number of wins by swtiching
    switch_wins <- switch_wins + 1
  }
}
# Calculate the probabilities of winning by staying and by switching
prob_stay <- stay_wins / sims
prob_switch <- switch_wins / sims

print(prob_stay)
print(prob_switch)
```